/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;

import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mazharul Islam
 */
public class addMovie extends javax.swing.JFrame {

    /**
     * Creates new form addMovie
     *
     */
    public addMovie() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        movieName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        movieDirector = new javax.swing.JTextField();
        movieLength = new javax.swing.JTextField();
        movieRating = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cencelButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        genreComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        url = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/loginFormBackground.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(600, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Movie");
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Movie Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        movieName.setBackground(new java.awt.Color(0, 0, 51));
        movieName.setForeground(new java.awt.Color(255, 255, 255));
        movieName.setMaximumSize(null);
        movieName.setMinimumSize(null);
        movieName.setName(""); // NOI18N
        movieName.setPreferredSize(new java.awt.Dimension(80, 30));
        movieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieNameActionPerformed(evt);
            }
        });
        getContentPane().add(movieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 147, 240, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Genre      :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 196, 93, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Director   :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 244, 93, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Length     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 292, 93, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Rating      :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 340, 93, -1));

        movieDirector.setBackground(new java.awt.Color(0, 0, 51));
        movieDirector.setForeground(new java.awt.Color(255, 255, 255));
        movieDirector.setMaximumSize(null);
        movieDirector.setMinimumSize(null);
        movieDirector.setName(""); // NOI18N
        movieDirector.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(movieDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 243, 238, -1));

        movieLength.setBackground(new java.awt.Color(0, 0, 51));
        movieLength.setForeground(new java.awt.Color(255, 255, 255));
        movieLength.setMaximumSize(null);
        movieLength.setMinimumSize(null);
        movieLength.setName(""); // NOI18N
        movieLength.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(movieLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 291, 238, -1));

        movieRating.setBackground(new java.awt.Color(0, 0, 51));
        movieRating.setForeground(new java.awt.Color(255, 255, 255));
        movieRating.setMaximumSize(null);
        movieRating.setMinimumSize(null);
        movieRating.setName(""); // NOI18N
        movieRating.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(movieRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 339, 238, -1));

        addButton.setBackground(new java.awt.Color(0, 0, 51));
        addButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-ok-25.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 147, -1));

        cencelButton.setBackground(new java.awt.Color(0, 0, 51));
        cencelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cencelButton.setForeground(new java.awt.Color(255, 255, 255));
        cencelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-unavailable-25.png"))); // NOI18N
        cencelButton.setText("Cancel");
        cencelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cencelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cencelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Name      : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 148, 91, -1));

        backButton.setBackground(new java.awt.Color(0, 0, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-back-40.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 25, -1, -1));

        genreComboBox.setBackground(new java.awt.Color(0, 0, 51));
        genreComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genreComboBox.setForeground(new java.awt.Color(255, 255, 255));
        genreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTION", "ADVENTURE", "ANIMATION", "BIOGRAPHY", "COMEDY", "CRIME", "DOCUMENTARY", "DRAMA", "FICTION", "FANTASY", "HORROR", "MUSICAL", "NOIR", "ROMANCE", "SCIENCE_FICTION", "SCIENCE", "SPORTS", "THRILLER", "WAR" }));
        genreComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(genreComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 198, 238, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Image Url:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        url.setBackground(new java.awt.Color(0, 0, 51));
        url.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(url, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 387, 238, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/Background1.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieNameActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String genre = genreComboBox.getSelectedItem().toString();
        if (this.movieName.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Movie Name Required");
        } else if (genre.length() == 0) {
            JOptionPane.showMessageDialog(null, "Movie Genre Required");
        } else if (this.movieDirector.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Movie Director Required");
        } else if (this.movieLength.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Movie Length Required");
        } else if (this.movieRating.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Movie Rating Required");
        } else if (this.movieRating.getText().length() != 0
                && (Float.parseFloat(this.movieRating.getText()) < 0
                || Float.parseFloat(this.movieRating.getText()) > 10)) {
            JOptionPane.showMessageDialog(null, "Rating must be beteween 0-10!");
        } else if (movie.checkMovie(this.movieName.getText().toUpperCase()) == null) {
            if (movie.requestExists(this.movieName.getText().toUpperCase())) {
                movie.deleteRequest(this.movieName.getText().toUpperCase());
            }
            movie.add(this.movieName.getText().toUpperCase(), genre.toUpperCase(), this.movieDirector.getText().toUpperCase(),
                    this.movieLength.getText(), this.movieRating.getText(), this.url.getText());
            JOptionPane.showMessageDialog(null, "Movie added Successfully");
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Movie exists");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cencelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cencelButtonActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_cencelButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void genreComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cencelButton;
    private javax.swing.JComboBox<String> genreComboBox;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField movieDirector;
    private javax.swing.JTextField movieLength;
    private javax.swing.JTextField movieName;
    private javax.swing.JTextField movieRating;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
}
