/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mazharul Islam
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allMovie = new javax.swing.JButton();
        searchMovie = new javax.swing.JButton();
        contactUsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        requestMovieButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Mode");
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allMovie.setBackground(new java.awt.Color(0, 51, 51));
        allMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        allMovie.setForeground(new java.awt.Color(255, 255, 255));
        allMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-movie-35.png"))); // NOI18N
        allMovie.setText("All Movie");
        allMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMovieActionPerformed(evt);
            }
        });
        getContentPane().add(allMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 233, 52));

        searchMovie.setBackground(new java.awt.Color(0, 51, 51));
        searchMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchMovie.setForeground(new java.awt.Color(255, 255, 255));
        searchMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-search-35.png"))); // NOI18N
        searchMovie.setText("Search Movie");
        searchMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMovieActionPerformed(evt);
            }
        });
        getContentPane().add(searchMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 233, 52));

        contactUsButton.setBackground(new java.awt.Color(0, 51, 51));
        contactUsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contactUsButton.setForeground(new java.awt.Color(255, 255, 255));
        contactUsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-contact-us-35.png"))); // NOI18N
        contactUsButton.setText("Contact Us");
        contactUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactUsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(contactUsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 233, 52));

        logoutButton.setBackground(new java.awt.Color(0, 51, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-logout-rounded-left-35.png"))); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 233, 52));

        requestMovieButton.setBackground(new java.awt.Color(0, 51, 51));
        requestMovieButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        requestMovieButton.setForeground(new java.awt.Color(255, 255, 255));
        requestMovieButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-request-service-35.png"))); // NOI18N
        requestMovieButton.setText("Request Movie");
        requestMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMovieButtonActionPerformed(evt);
            }
        });
        getContentPane().add(requestMovieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 233, 52));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/Background1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int value = JOptionPane.showConfirmDialog(null, "Are you sure?", "Warning", JOptionPane.YES_NO_OPTION);
        if (value == 0) {
            this.setVisible(false);
            new userForm().setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void contactUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactUsButtonActionPerformed
        new contactUs().setVisible(true);
    }//GEN-LAST:event_contactUsButtonActionPerformed

    private void searchMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMovieActionPerformed
        this.setVisible(false);
        new searchMovie().setVisible(true);
    }//GEN-LAST:event_searchMovieActionPerformed

    private void allMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMovieActionPerformed
        if (movie.countMovie()) {
            this.setVisible(false);
            String s = movie.allMovie();
            new allMovie(s, 0).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Movie Database is Empty:(");
        }
    }//GEN-LAST:event_allMovieActionPerformed

    private void requestMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMovieButtonActionPerformed
        new requestMovie().setVisible(true);
    }//GEN-LAST:event_requestMovieButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allMovie;
    private javax.swing.JButton contactUsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton requestMovieButton;
    private javax.swing.JButton searchMovie;
    // End of variables declaration//GEN-END:variables
}
