/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;

import javax.swing.JFrame;

/**
 *
 * @author Mazharul Islam
 */
public class requestedMovie extends javax.swing.JFrame {

    private String movieName[], s;
    private int currentIndex;

    /**
     * Creates new form requestedMovie
     *
     * @param s
     */
    public requestedMovie(String s) {
        initComponents();
        this.s = movie.allMovieRequest();
        this.setMovie();
        this.setTextField();
        this.setButton();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public requestedMovie() {
        initComponents();
        this.s = movie.allMovieRequest();
        this.setMovie();
        this.setTextField();
        this.setButton();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void setMovie() {
        if (this.s.length() == 0) {
            this.currentIndex = -1;
        } else {
            movieName = this.s.split("\\,");
            this.currentIndex = 0;
        }
    }

    private void setTextField() {
        if (this.currentIndex == -1) {
            this.currentMovieName.setText("No movie request!");
        } else {
            this.currentMovieName.setText(this.movieName[this.currentIndex]);
        }
        this.currentMovieName.setEditable(false);
    }

    private void setButton() {
        if (this.currentIndex == -1) {
            this.previousButton.setEnabled(false);
            this.nextButton.setEnabled(false);
        } else {
            if (this.currentIndex == 0) {
                this.previousButton.setEnabled(false);
            } else {
                this.previousButton.setEnabled(true);
            }
            if (this.currentIndex == movieName.length - 1) {
                this.nextButton.setEnabled(false);
            } else {
                this.nextButton.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentMovieName = new javax.swing.JTextField();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Requested Movie");
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentMovieName.setBackground(new java.awt.Color(0, 0, 51));
        currentMovieName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        currentMovieName.setForeground(new java.awt.Color(255, 255, 255));
        currentMovieName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(currentMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 154, 270, 130));

        previousButton.setBackground(new java.awt.Color(0, 0, 51));
        previousButton.setForeground(new java.awt.Color(255, 255, 255));
        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-back-arrow-40.png"))); // NOI18N
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        getContentPane().add(previousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 333, 100, -1));

        nextButton.setBackground(new java.awt.Color(0, 0, 51));
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/icons8-forward-button-40.png"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 333, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedatabase/Images/Background1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (this.currentIndex < movieName.length - 1) {
            this.currentIndex = this.currentIndex + 1;
            this.setTextField();
            this.setButton();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (this.currentIndex > 0) {
            this.currentIndex = this.currentIndex - 1;
            this.setTextField();
            this.setButton();
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(requestedMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(requestedMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(requestedMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(requestedMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new requestedMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentMovieName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
